### ISSUE TITLE
Inconsistent spacing between post listings

### ISSUE THREAD

**Issue by riklopfer** [allnightgrocery/hugo-theme-blueberry-detox#3]
The spacing between post listings is not uniform. This can be seen on the [demo page](http://themes.gohugo.io/theme/detox/). The spacing between the first two posts is much smaller than between any others.

**Comment by allnightgrocery** [comment]
Got it. I'll take a look. (Sorry for the delay, I don't know why I didn't get a notice of an opened issue.)
