### ISSUE TITLE
meta keywords has placeholder text

### ISSUE THREAD

**Issue by mathewreny** [allnightgrocery/hugo-theme-blueberry-detox#7]
In the meta.html partial you have the following line that has placeholder text.

```
<meta name="keywords" content="awesome, definitely">
```

**Comment by allnightgrocery** [comment]
May I ask what you're getting at with your observation? I'm not sure I'm following.

**Comment by mathewreny** [comment]
https://github.com/allnightgrocery/hugo-theme-blueberry-detox/blob/master/layouts/partials/meta.html#L9

You have placeholder text here.

**Comment by allnightgrocery** [comment]
Yes, I have the placeholder text from the original port. Are you suggesting I change this or make it configurable?

**Comment by mathewreny** [comment]
It would probably be best to make it configurable or leave it out entirely.  Unless it's noted in documentation, I tend to discourage the use of placeholder text.  I created the issue because thought it was a simple oversight.  If you don't feel like it's a bad thing feel free to close the issue.  The theme is nice btw.

**Comment by allnightgrocery** [comment]
Not a bad suggestion at all. I wasn't quite sure why you were making the observation, thus my questions. I left Jordan's theme as pure as possible, out of respect for his hard work and his beautiful theme, but it probably wouldn't hurt to make the metadata a bit more "usable". Thanks!

I'll leave this open until I can resolve properly.
